name: Atualizar README
on:
  push:
    branches:
      - master
jobs:
  atualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
      - name: Usar readme-scribe
        uses: gleriston/readme-scribe@master
